title: bytv work menual
email: ltg@bbangyanetworks.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl:  # the subpath of your site, e.g. /blog
url: https://ltg2004.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: false
github_username: ltg@bbangyanetworks.com
author: ltg@bbangyanetworks.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]

# Site Logo
logo: https://static.bbangyatv.com/web/nav/bytv_logo_blue.png

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# nav sort
nav_sort: case_sensitive

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Header
heading_anchors: true

# Footer content
footer_content: '&copy; 2021 BBANGYA NETWORKS Co,. Ltd. All rights reserved.'

# Color scheme
color_scheme: dark

# Google Analytics
ga_tracking: G-4ZN8WZYT1D
ga_tracking_anonymize_ip: true

collections:
  vue:
    permalink: '/:collection/:path/'
    output: true
  jest:
    permalink: '/:collection/:path/'
    output: true
  authors:
    permalink: '/:collection/:path/'
    output: true

just_the_docs:
  collections:
    vue:
      name: Vue.js
    jest:
      name: Jest
    authors:
      name: Authors
      nav_exclude: false
      search_exclude: false

# Build settings
theme: 'just-the-docs'

plugins:
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

exclude:
  - Gemfile
  - Gemfile.lock
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
